services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stark
      POSTGRES_PASSWORD: stark
      POSTGRES_DB: starkbank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
